pipeline:
  pre-commit:
    group: test
    image: python:alpine
    when:
      event: pull_request
      branch: main
      matrix:
        PYTHON_VERSION: "3.11"
    commands:
      - apk --no-cache add git
      - python -m pip install pre-commit
      - |
        if [[ "$CI_BUILD_EVENT" == "pull_request" ]]; then
          git fetch origin $CI_COMMIT_BRANCH
          pre-commit run --from-ref origin/$CI_COMMIT_BRANCH --to-ref $CI_COMMIT_SHA
        else
          pre-commit run --all-files
        fi

  test:
    group: test
    image: python:${PYTHON_VERSION}-alpine
    when:
      event:
        - pull_request
        - push
      branch: main

    commands:
      - apk --no-cache add git
      - python -m pip install tox
      - tox run -s

matrix:
  PYTHON_VERSION:
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"
    - "3.11"

branches: main
